use std::{collections::HashMap, fs, path::PathBuf, time::Instant};

use anyhow::{Result, bail};

use clap::Parser;

use object::{Object, read::pe::PeFile64};

use pdb_wrapper::{PDB, PDBType, StructField, pdb_meta::SimpleTypeKind};

use regex::Regex;

use serde::{Deserialize, Deserializer};

#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]

struct PdbArgs {
    #[arg(
        short,
        long,
        default_value = "il2cpp_dump.json",
        help = "path to il2cpp dump generated by reframework"
    )]
    il2cpp: String,

    #[arg(
        short,
        long,
        help = "path to the game exe, e.g 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\MonsterHunterWilds\\MonsterHunterWilds.exe'"
    )]
    exe: String,

    #[arg(
        short,
        long,
        help = "path to the output directory, e.g 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\MonsterHunterWilds'. If unspecified, it will be written to the location of the exe"
    )]
    output: Option<String>,

    #[arg(
        short,
        long,
        help = "name of the pdb file (file will be written as \"<name>.pdb\", default uses the name of the exe)"
    )]
    name: Option<String>,

    #[arg(
        short,
        long,
        help = "override for the age that will be written to the pdb file"
    )]
    age: Option<u32>,

    #[arg(
        short,
        long,
        help = "override for the signature that will be written to the pdb file (default=0)"
    )]
    signature: Option<u32>,

    #[arg(
        short,
        long,
        help = "override for the guid that will be written to the pdb file"
    )]
    guid: Option<String>,

    #[arg(short, long, help = "regex filter for types to add")]
    filter: Option<String>,

    #[arg(short, long)]
    verbose: bool,

    #[arg(
        short,
        long,
        default_value_t = 0x140000000,
        help = "base address of the exe, types get added to the pdb relative to the 0th segment"
    )]
    base_address: u64,
}

#[allow(unused)]
#[derive(Debug, Deserialize)]

pub struct REType {
    #[serde(skip)]
    name: String,

    #[serde(default, deserialize_with = "parse_address_u64")]
    address: u64,

    #[serde(deserialize_with = "parse_address_u32")]
    crc: u32,

    #[serde(default, deserialize_with = "deserialize_fields")]
    fields: HashMap<String, REField>,

    #[serde(deserialize_with = "parse_address_u64")]
    fqn: u64,

    #[serde(default)]
    is_generic_type: bool,

    #[serde(default)]
    is_generic_type_definition: bool,

    #[serde(default, deserialize_with = "deserialize_methods")]
    methods: HashMap<String, REMethod>,

    #[serde(default)]
    name_hierarchy: Vec<String>,

    #[serde(default)]
    properties: HashMap<String, REProperty>,

    #[serde(deserialize_with = "parse_address_u32")]
    #[serde(default)]
    size: u32,
}

impl REType {
    pub fn get_struct_fields(&self) -> Result<Vec<StructField>> {
        let mut struct_fields = vec![];

        for (f_name, field) in &self.fields {
            if let Ok(ty) = field.to_pdb_type() {
                let sf = StructField {
                    ty,

                    name: f_name.clone(),

                    offset: field.offset_from_base as u64,
                };

                struct_fields.push(sf);
            }
        }

        struct_fields.sort_by_key(|f| f.offset);

        Ok(struct_fields)
    }
}

#[allow(unused)]
#[derive(Debug, Deserialize)]

pub struct REField {
    #[serde(skip)]
    name: String,

    id: u32,

    init_data_index: u32,

    #[serde(deserialize_with = "parse_address_u32")]
    offset_from_base: u32,

    #[serde(deserialize_with = "parse_address_u32")]
    offset_from_fieldptr: u32,

    r#type: String,
}

impl REField {
    pub fn to_pdb_type(&self) -> Result<PDBType> {
        let t = match self.r#type.as_str() {
            "System.Boolean" => PDBType::SimpleType(SimpleTypeKind::Boolean8),

            "System.SByte" => PDBType::SimpleType(SimpleTypeKind::SByte),

            "System.Int16" => PDBType::SimpleType(SimpleTypeKind::Int16),

            "System.Int32" => PDBType::SimpleType(SimpleTypeKind::Int32),

            "System.Int64" => PDBType::SimpleType(SimpleTypeKind::Int64),

            "System.Byte" => PDBType::SimpleType(SimpleTypeKind::Byte),

            "System.UInt16" => PDBType::SimpleType(SimpleTypeKind::UInt16),

            "System.UInt32" => PDBType::SimpleType(SimpleTypeKind::UInt32),

            "System.UInt64" => PDBType::SimpleType(SimpleTypeKind::UInt64),

            "System.Single" => PDBType::SimpleType(SimpleTypeKind::Float32),

            "System.Double" => PDBType::SimpleType(SimpleTypeKind::Float64),

            "System.Char" => PDBType::SimpleType(SimpleTypeKind::WideCharacter),

            "System.Guid" => {
                PDBType::ConstantArray(Box::new(PDBType::SimpleType(SimpleTypeKind::Byte)), 8)
            }

            _ => PDBType::Pointer(Box::new(PDBType::Struct(self.name.clone()))),
            //_ => bail!("Unmatched type"),
        };

        Ok(t)
    }
}

#[allow(unused)]
#[derive(Debug, Deserialize)]

pub struct REMethod {
    #[serde(skip)]
    name: String,

    flags: Option<String>,

    #[serde(deserialize_with = "parse_address_u64")]
    function: u64,

    id: u32,

    impl_flags: Option<String>,

    invoke_id: u32,

    params: Option<Vec<REParam>>,

    returns: Option<REParam>,

    vtable_index: Option<u32>,
}

impl REMethod {
    pub fn signature(&self, r#type: &REType) -> String {
        let params = self
            .params
            .as_ref()
            .map(|p| {
                let mut params = String::new();

                for (i, param) in p.iter().enumerate() {
                    params.push_str(&param.r#type);

                    if !param.name.is_empty() {
                        params.push(' ');

                        params.push_str(&param.name);
                    }

                    if i != p.len() {
                        params.push(',');
                    }
                }

                params
            })
            .unwrap_or("".to_string());

        let signature = format!("{}::{}({})", r#type.name, self.name, params);

        signature
    }
}

#[allow(unused)]
#[derive(Debug, Deserialize)]

pub struct REParam {
    name: String,

    r#type: String,
}

#[allow(unused)]
#[derive(Debug, Deserialize)]

pub struct REProperty {
    #[serde(skip)]
    name: String,

    getter: String,

    id: u32,

    setter: String,
}

pub type Il2Cpp = HashMap<String, REType>;

pub fn parse_address_u64<'de, D>(deserializer: D) -> Result<u64, D::Error>
where
    D: Deserializer<'de>,
{
    let s = String::deserialize(deserializer)?;

    let clean_str = s.trim_start_matches("0x");

    u64::from_str_radix(clean_str, 16).map_err(serde::de::Error::custom)
}

pub fn parse_address_u32<'de, D>(deserializer: D) -> Result<u32, D::Error>
where
    D: Deserializer<'de>,
{
    let s = String::deserialize(deserializer)?;

    let clean_str = s.trim_start_matches("0x");

    u32::from_str_radix(clean_str, 16).map_err(serde::de::Error::custom)
}

fn deserialize_fields<'de, D>(deserializer: D) -> Result<HashMap<String, REField>, D::Error>
where
    D: Deserializer<'de>,
{
    let mut map: HashMap<String, REField> = HashMap::deserialize(deserializer)?;

    for (key, t_data) in map.iter_mut() {
        t_data.name = key.clone();
    }

    Ok(map)
}

fn deserialize_methods<'de, D>(deserializer: D) -> Result<HashMap<String, REMethod>, D::Error>
where
    D: Deserializer<'de>,
{
    let mut map: HashMap<String, REMethod> = HashMap::deserialize(deserializer)?;

    for (key, t_data) in map.iter_mut() {
        t_data.name = key.clone();
    }

    Ok(map)
}

fn deserialize_il2cpp<'de, D>(deserializer: D) -> Result<Il2Cpp, D::Error>
where
    D: Deserializer<'de>,
{
    let mut map: HashMap<String, REType> = HashMap::deserialize(deserializer)?;

    for (key, t_data) in map.iter_mut() {
        t_data.name = key.clone();
    }

    Ok(map)
}

// age, signature, guid

fn get_pdb_info(args: &PdbArgs, pe: &PeFile64) -> Result<(u32, u32, [u8; 16])> {
    let mut age = 0;

    let mut guid = [0; 16];

    let mut signature = 0;

    if let Some(pdb_info) = pe.pdb_info()? {
        age = pdb_info.age();

        guid = pdb_info.guid();
    }

    if let Some(a) = args.age {
        age = a;
    }

    if let Some(g) = &args.guid {
        guid = uuid::Uuid::parse_str(&g)?.to_bytes_le();
    }

    if let Some(s) = args.signature {
        signature = s;
    }

    Ok((age, signature, guid))
}

fn add_types(pdb: &mut PDB, il2cpp: &Il2Cpp, addr_offset: u64, verbose: bool) -> Result<()> {
    for (name, t) in il2cpp {
        if name.is_empty() {
            println!("[INFO] Skipping {name:?} (empty)");

            continue;
        }

        if verbose {
            println!("Adding Type {name}");
        }

        let struct_fields = t.get_struct_fields()?;

        pdb.insert_struct(&name, &struct_fields, t.size as u64)?;

        for (_f_name, function) in &t.methods {
            if function.function != 0 {
                let signature = function.signature(t);

                if verbose {
                    println!("\tAdding function {}@{:x}", signature, function.function);
                }

                let offset_addr = (function.function - addr_offset) as u32;

                pdb.insert_function(0, offset_addr, &signature, None)?;
            }
        }
    }

    Ok(())
}

fn main() -> Result<()> {
    let args = PdbArgs::parse();

    println!("[INFO] Loading il2cpp from {}", args.il2cpp);

    let il2cpp = std::fs::read_to_string(&args.il2cpp)?;

    let mut deserializer = serde_json::Deserializer::from_str(&il2cpp);

    let mut il2cpp = deserialize_il2cpp(&mut deserializer)?;

    if let Some(re) = &args.filter {
        let regex = Regex::new(&re)?;

        println!("[INFO] Filtering for \"{re}\"");

        il2cpp.retain(|k, _| regex.is_match(&k));
    }

    println!("[INFO] Finished loading il2cpp");

    println!("[INFO] Loading exe from {}", args.exe);

    let data = fs::read(&args.exe)?;

    let pe = PeFile64::parse(&*data)?;

    let is_64 = pe.is_64();

    if !is_64 {
        println!("[WARNING] exe is not 64-bit");
    }

    let (age, signature, guid) = get_pdb_info(&args, &pe)?;

    println!(
        "[INFO] age={age}, signature={signature}, guid={}",
        uuid::Uuid::from_bytes_le(guid)
    );

    let mut pdb = PDB::new(is_64, age, 0, guid).unwrap();

    let addr_offset = args.base_address;

    let start_time = Instant::now();

    println!("[INFO] Adding {} il2cpp types", il2cpp.len());

    add_types(&mut pdb, &il2cpp, addr_offset, args.verbose)?;

    println!(
        "[INFO] Completed in {}s",
        start_time.elapsed().as_secs_f32()
    );

    // ye idk wtf this is lol but whatever

    let exe_path = PathBuf::from(&args.exe);

    let mut output = args.output.map(|o| PathBuf::from(o)).unwrap_or_else(|| {
        exe_path
            .parent()
            .map(|x| x.to_path_buf())
            .unwrap_or(PathBuf::new())
    });

    let file_name = args.name.unwrap_or_else(|| {
        exe_path
            .file_prefix()
            .map(|x| x.to_string_lossy().to_string())
            .unwrap_or("generated".into())
    });

    let pdb_file_name = format!("{file_name}.pdb");

    output.push(pdb_file_name);

    let output = output.to_string_lossy().to_string();

    println!("[INFO] Outputting to {output}");

    pdb.commit(&args.exe, &output)?;

    Ok(())
}
